#!/bin/bash

# Build script for PillSnap web
# This script processes environment variables and prepares files for deployment

echo "🚀 Building PillSnap web..."

# Debug: Print environment info
echo "Environment variables status:"
echo "GA_MEASUREMENT_ID: ${GA_MEASUREMENT_ID:-'not set'}"
echo "CF_BEACON_TOKEN: ${CF_BEACON_TOKEN:-'not set'}"
echo "WEB3FORMS_ACCESS_KEY: ${WEB3FORMS_ACCESS_KEY:-'not set'}"

# Load environment variables from .env if running locally
if [ -f .env ]; then
    echo "Loading from .env file..."
    export $(cat .env | grep -v '^#' | xargs)
else
    echo "⚠️  Warning: .env file not found. Using environment variables from Cloudflare Pages."
fi

# Set defaults if still not set
GA_MEASUREMENT_ID="${GA_MEASUREMENT_ID:-GA_MEASUREMENT_ID}"
CF_BEACON_TOKEN="${CF_BEACON_TOKEN:-CF_BEACON_TOKEN}"
WEB3FORMS_ACCESS_KEY="${WEB3FORMS_ACCESS_KEY:-WEB3FORMS_ACCESS_KEY}"

# Create config.js with environment variables
cat > assets/js/config.js << EOF
// Configuration loaded from environment variables
// Auto-generated by build.sh - DO NOT EDIT DIRECTLY
window.APP_CONFIG = {
  // Google Analytics
  GA_MEASUREMENT_ID: '${GA_MEASUREMENT_ID:-GA_MEASUREMENT_ID}',
  
  // Cloudflare Web Analytics  
  CF_BEACON_TOKEN: '${CF_BEACON_TOKEN:-CF_BEACON_TOKEN}',
  
  // Web3Forms
  WEB3FORMS_ACCESS_KEY: '${WEB3FORMS_ACCESS_KEY:-WEB3FORMS_ACCESS_KEY}'
};
EOF

echo "✅ Config file generated"

# Process HTML files to inject analytics scripts
for file in *.html; do
    echo "Processing $file..."
    
    # Create temporary file
    temp_file="${file}.tmp"
    
    # Replace placeholders in HTML files
    sed -e "s/GA_MEASUREMENT_ID/${GA_MEASUREMENT_ID:-GA_MEASUREMENT_ID}/g" \
        -e "s/CF_BEACON_TOKEN/${CF_BEACON_TOKEN:-CF_BEACON_TOKEN}/g" \
        -e "s/WEB3FORMS_ACCESS_KEY/${WEB3FORMS_ACCESS_KEY:-WEB3FORMS_ACCESS_KEY}/g" \
        "$file" > "$temp_file"
    
    mv "$temp_file" "$file"
done

echo "✅ HTML files processed"

# Check if running in production (GitHub Actions)
if [ "$GITHUB_ACTIONS" = "true" ]; then
    echo "📦 Running in GitHub Actions - using secrets"
else
    echo "💻 Running locally - using .env file"
fi

echo "🎉 Build complete!"