#!/bin/bash

# Build script for PillSnap web
# This script processes environment variables and prepares files for deployment

echo "🚀 Building PillSnap web..."

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | xargs)
fi

# Create config.js with environment variables
cat > assets/js/config.js << EOF
// Configuration loaded from environment variables
// Auto-generated by build.sh - DO NOT EDIT DIRECTLY
window.APP_CONFIG = {
  // Google Analytics
  GA_MEASUREMENT_ID: '${GA_MEASUREMENT_ID:-G-XXXXXXXXXX}',
  
  // Cloudflare Web Analytics  
  CF_BEACON_TOKEN: '${CF_BEACON_TOKEN:-YOUR_TOKEN_HERE}',
  
  // Web3Forms
  WEB3FORMS_ACCESS_KEY: '${WEB3FORMS_ACCESS_KEY:-f6faf7e3-fa62-4ff3-b7d8-1b31df67831b}'
};
EOF

echo "✅ Config file generated"

# Process HTML files to inject analytics scripts
for file in *.html; do
    echo "Processing $file..."
    
    # Create temporary file
    temp_file="${file}.tmp"
    
    # Replace placeholders in HTML files
    sed -e "s/G-XXXXXXXXXX/${GA_MEASUREMENT_ID:-G-XXXXXXXXXX}/g" \
        -e "s/YOUR_TOKEN_HERE/${CF_BEACON_TOKEN:-YOUR_TOKEN_HERE}/g" \
        -e "s/f6faf7e3-fa62-4ff3-b7d8-1b31df67831b/${WEB3FORMS_ACCESS_KEY:-f6faf7e3-fa62-4ff3-b7d8-1b31df67831b}/g" \
        "$file" > "$temp_file"
    
    mv "$temp_file" "$file"
done

echo "✅ HTML files processed"
echo "🎉 Build complete!"